# Generated by Django 3.2.7 on 2022-10-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_certificate', models.FileField(upload_to='')),
                ('phone_number', models.CharField(max_length=100)),
                ('id_certificate', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('year_of_completion', models.IntegerField()),
                ('recommendation_letter', models.FileField(upload_to='')),
                ('reason_sponsorship', models.TextField()),
                ('academic_level', models.CharField(max_length=100)),
                ('sponsorship_status', models.CharField(default='Complete', max_length=100)),
                ('approval_status', models.CharField(default='Approved', max_length=100)),
            ],
        ),
    ]
