# Generated by Django 3.2.7 on 2022-10-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvedApplications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedapplications',
            old_name='academic_level',
            new_name='academicLevel',
        ),
        migrations.RenameField(
            model_name='approvedapplications',
            old_name='year_of_completion',
            new_name='completionYear',
        ),
        migrations.RenameField(
            model_name='approvedapplications',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='approvedapplications',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='approvedapplications',
            old_name='last_name',
            new_name='homeAddress',
        ),
        migrations.RenameField(
            model_name='approvedapplications',
            old_name='phone_number',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='approvedapplications',
            old_name='reason_sponsorship',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='approvedapplications',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='approvedapplications',
            name='birth_certificate',
        ),
        migrations.RemoveField(
            model_name='approvedapplications',
            name='id_certificate',
        ),
        migrations.RemoveField(
            model_name='approvedapplications',
            name='recommendation_letter',
        ),
        migrations.RemoveField(
            model_name='approvedapplications',
            name='sponsorship_status',
        ),
        migrations.AddField(
            model_name='approvedapplications',
            name='certFile',
            field=models.FileField(blank=True, upload_to='Documents'),
        ),
        migrations.AddField(
            model_name='approvedapplications',
            name='idFile',
            field=models.FileField(blank=True, upload_to='Documents'),
        ),
        migrations.AddField(
            model_name='approvedapplications',
            name='phone',
            field=models.IntegerField(default=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedapplications',
            name='schoolAddress',
            field=models.CharField(default=124, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedapplications',
            name='schoolName',
            field=models.CharField(default=14, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedapplications',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
