# Generated by Django 3.2.7 on 2022-10-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('idFile', models.FileField(blank=True, upload_to='Documents')),
                ('certFile', models.FileField(blank=True, upload_to='Documents')),
                ('schoolName', models.CharField(max_length=100)),
                ('schoolAddress', models.CharField(max_length=100)),
                ('academicLevel', models.CharField(max_length=100)),
                ('completionYear', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('sponsorName', models.CharField(max_length=100)),
                ('sponsorPhoneNumber', models.IntegerField()),
            ],
        ),
    ]
